## ===== SPLUNK =====

spl:
  type: "detection_language"
  name: "SPL"
  description: "Splunk Processing Language"
  products:
    - "Splunk Enterprise"
    - "Splunk Enterprise Security"
  documentation: "https://docs.splunk.com/Documentation/SplunkCloud/latest/SearchReference/WhatsInThisManual"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== Sentinel =====

kql:
  type: "detection_language"
  name: "KQL"
  description: "Kusto Query Language"
  products:
    - "Microsoft Sentinel"
  documentation: "https://learn.microsoft.com/en-us/kusto/query/?view=microsoft-fabric"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== Elastic =====

elastic_dsl:
  type: "detection_language"
  name: "Elasticsearch Query DSL"
  description: "Elasticsearch Query DSL (Domain-Specific Language)"
  products:
    - "Elastic"
    - "Elastic Security"
  documentation: "https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== Chronicle =====

yara-l-2:
  type: "detection_language"
  name: "YARA-L 2.0"
  description: ""
  products:
    - "Google Chronicle"
  documentation: "https://cloud.google.com/chronicle/docs/detection/yara-l-2-0-overview"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== Sigma =====

sigma:
  type: "detection_language"
  name: "Sigma"
  description: "https://sigmahq.io/docs/basics/rules.html"
  products:
    -
  documentation: ""
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0