## ===== APACHE =====

apache_access_combined:
  type: "log"
  product: "apache"
  name: "access_combined"
  description: "access_combined logs are a common format used by web servers, such as Apache HTTP Server, to log incoming HTTP requests. These logs provide detailed information about client requests to a server, including the client’s IP address, the request method, the requested resource, and the response code. The access_combined log format is an extension of the access_common log format, with additional fields such as the referrer URL and the user-agent string."
  samples: 
    - "log_samples/apache/access_combined.log"
  tags:
    - "webserver"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0
apache_error:
  type: "log"
  product: "apache"
  name: "error"
  description: "The apache_error log is used by the Apache HTTP Server to record server errors, warnings, and diagnostic information. This log file is essential for troubleshooting server issues, debugging, and monitoring the health of the server. It contains error messages, configuration issues, module errors, and runtime issues such as script errors or problems with client requests."
  samples: 
    - "log_samples/apache/error.log"
  tags:
    - "webserver"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== AWS =====

amazon_web_services_cloudtrail:
  type: "log"
  product: "amazon_web_services"
  name: "cloudtrail"
  description: "AWS CloudTrail logs are used to record API calls made to AWS services. These logs capture detailed information about each request, including the event source, the API operation invoked, the user who made the request, the result, and other context, such as the IP address of the requester and the resources involved. CloudTrail logs are critical for auditing and monitoring activities in your AWS account, providing visibility into actions that affect your AWS infrastructure."
  samples: 
    - "log_samples/amazon_web_services/cloudtrail.json"
  tags:
    - "platform"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== GCP =====

google_cloud_platform_generic:
  type: "log"
  product: "google_cloud_platform"
  name: "generic"
  description: "GCP logs are typically generated by Google Cloud Logging, which collects and stores logs from various Google Cloud services like Compute Engine, Cloud Storage, Cloud Functions, BigQuery, and more. These logs include detailed information about events, operations, and errors occurring within your GCP resources. They are essential for monitoring, auditing, and troubleshooting in GCP environments."
  samples: 
    - "log_samples/google_cloud_platform/generic.json"
  tags:
    - "platform"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

## ===== Linux =====

linux_auditd:
  type: "log"
  product: "linux"
  name: "auditd"
  description: "Auditd is the Linux Audit Daemon that provides logging for a wide range of security-related events on a Linux system. The auditd service is often used for tracking system calls, monitoring file access, logging user activity, and auditing privileged operations. These logs are essential for ensuring compliance, monitoring security, and troubleshooting issues on Linux systems."
  samples: 
    - "log_samples/linux/auditd.log"
  tags:
    - "os"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

linux_secure:
  type: "log"
  product: "linux"
  name: "secure"
  description: "The Linux Secure Logs capture security-related events, including authentication attempts (both successful and failed), sudo commands, user logins, SSH activity, and other privileged activities. These logs are essential for monitoring and auditing security-related actions on a Linux system."
  samples: 
    - "log_samples/linux/secure.log"
  tags:
    - "os"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0

linux_ps:
  type: "log"
  product: "linux"
  name: "ps"
  description: "The ps command in Linux is used to display information about running processes. Its not a log by itself but rather a tool to view real-time information about processes in the system. However, the output from the ps command can be logged or saved for auditing or troubleshooting purposes."
  samples: 
    - "log_samples/linux/ps.log"
  tags:
    - "os"
  created: 2020-01-01
  modified:  2020-01-01
  created_by: DOGESEC
  version: 1.0.0