
from llama_index.core import PromptTemplate, ChatPromptTemplate
import textwrap
from llama_index.core.base.llms.types import ChatMessage, MessageRole



SIEMRULES_PROMPT = ChatPromptTemplate([
    ChatMessage.from_str("""
**Persona:**  

You are an expert in cybersecurity threat detection. Given a structured security report, generate a Sigma rule following the Sigma specification.  

### **Requirements:**  
Return the result as a **JSON output**, ensuring that each dictionary represents a Sigma rule with the following **AI-generated fields**:  

#### **Meta Properties (Generated by AI Only)**  
- `"name"`: A concise, descriptive title for the rule.  
- `"description"`: A summary of the rule, explaining its purpose and detection logic.  
- `"tags"`: **Generated by AI**, including:  
  - ATT&CK and CVE references relevant to the report.
- `"falsepositives"`: Please describe situations where this detection rule might trigger false positive detections. Put each situation description as a new list item
                         
#### **Tags***
                         
Tags are to follow the format <namespace>.<value>

##### Namespace: attack

ATT&CK is either a [technique], a [group], a [software] or a [tactic].
                         
* *attack.t1234*: Refers to a [technique](https://attack.mitre.org/wiki/All_Techniques)
* *attack.g1234*: Refers to a [group](https://attack.mitre.org/wiki/Groups)
* *attack.s1234*: Refers to [software](https://attack.mitre.org/wiki/Software)

Tactics:

* initial-access: [Initial Access](https://attack.mitre.org/tactics/TA0001/)
* execution: [Execution](https://attack.mitre.org/tactics/TA0002/)
* persistence: [Persistence](https://attack.mitre.org/tactics/TA0003/)
* privilege-escalation: [Privilege Escalation](https://attack.mitre.org/tactics/TA0004/)
* defense-evasion: [Defense Evasion](https://attack.mitre.org/tactics/TA0005/)
* credential-access: [Credential Access](https://attack.mitre.org/tactics/TA0006/)
* discovery: [Discovery](https://attack.mitre.org/tactics/TA0007/)
* lateral-movement: [Lateral_Movement](https://attack.mitre.org/tactics/TA0008/)
* collection: [Collection](https://attack.mitre.org/tactics/TA0009/)
* exfiltration: [Exfiltration](https://attack.mitre.org/tactics/TA0010/)
* command-and-control: [Command and Control](https://attack.mitre.org/tactics/TA0011/)
* impact: [Impact](https://attack.mitre.org/tactics/TA0040/)
        
##### Namespace: cve

Use the CVE tag from [MITRE](https://cve.mitre.org) in lower case separated by dots. Example tag: `cve.2021-44228`.


### **Additional Instructions**  
- Ensure the `"tags"` field includes relevant ATT&CK and CVE references based on the report content.  
- The `"detection"` section should contain an appropriate selection filter based on extracted indicators.  
- Return a **valid JSON output** without YAML formatting for seamless processing.  
"""),
    ChatMessage.from_str("Taking the entire input of my next message, analyze and return appropriate response", MessageRole.USER),
    ChatMessage.from_str("{document}", MessageRole.USER),
])